from __future__ import annotations

import platform
import time
from pathlib import Path
from typing import Any

import onnx

import ezkl_cli
from artifacts import (
    ARTIFACTS_DIR,
    CALIBRATION_PATH,
    COMPILED_CIRCUIT_PATH,
    FIXTURES_DIR,
    GENERATED_VERIFIER_DIR,
    MODEL_PATH,
    PROVING_KEY_PATH,
    SETTINGS_PATH,
    SRS_PATH,
    VERIFICATION_KEY_PATH,
    VERIFIER_ABI_PATH,
    VERIFIER_MANIFEST_PATH,
    VERIFIER_SOLIDITY_PATH,
    read_json,
    read_manifest,
    sha256_file,
    write_json,
    write_manifest,
)
from bundle import (
    artifact_paths_for_bundle,
    build_bundle,
    proof_document_from_bundle,
    validate_bundle,
    write_bundle,
)
from model import GRAPH_VARIANT, policy_graph_bytes
from normalization import fixture_to_ezkl_input
from report import write_proof_feasibility

CALIBRATION_FIXTURES = (
    "eligible.json",
    "ineligible.json",
    "boundary-age-18.json",
    "boundary-hba1c-5.7.json",
    "boundary-hba1c-8.5.json",
    "boundary-egfr-60.json",
)
REQUIRED_SETUP_ARTIFACTS = (
    MODEL_PATH,
    SETTINGS_PATH,
    COMPILED_CIRCUIT_PATH,
    SRS_PATH,
    PROVING_KEY_PATH,
    VERIFICATION_KEY_PATH,
)


class PipelineError(RuntimeError):
    pass


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise PipelineError(message)


def _assert_pinned_environment(manifest: dict[str, Any]) -> None:
    _require(platform.machine() == ezkl_cli.PINNED_EZKL_ARCH, "prover must run on aarch64")
    _require(
        ezkl_cli.version() == ezkl_cli.PINNED_EZKL_VERSION,
        "installed EZKL version does not match the pinned manifest",
    )
    _require(
        ezkl_cli.binary_sha256() == ezkl_cli.PINNED_EZKL_SHA256,
        "installed EZKL binary digest does not match the pin",
    )
    _require(
        manifest.get("ezklVersion") == ezkl_cli.PINNED_EZKL_VERSION,
        "manifest EZKL version mismatch; run npm run check:env",
    )
    _require(manifest.get("onnxVersion") == onnx.__version__, "manifest ONNX version mismatch")
    _require(manifest.get("graphVariant") == GRAPH_VARIANT, "manifest graph variant mismatch")


def _export_model() -> str:
    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    MODEL_PATH.write_bytes(policy_graph_bytes())
    return sha256_file(MODEL_PATH)


def _write_calibration_data() -> None:
    samples: list[int] = []
    for name in CALIBRATION_FIXTURES:
        sample = fixture_to_ezkl_input(FIXTURES_DIR / name)["input_data"][0]
        samples.extend(sample)
    write_json(CALIBRATION_PATH, {"input_data": [samples]})


def _validate_settings(settings: dict[str, Any]) -> None:
    run_args = settings.get("run_args", {})
    _require(run_args.get("input_scale") == 0, "calibration changed the exact integer input scale")
    _require(
        run_args.get("param_scale") == 0,
        "calibration changed the exact integer parameter scale",
    )
    _require(run_args.get("input_visibility") == "Private", "circuit input must remain private")
    _require(run_args.get("output_visibility") == "Public", "circuit output must remain public")
    _require(settings.get("model_instance_shapes") == [[1, 1]], "expected one public output")


def _validate_generated_verifier() -> None:
    source = VERIFIER_SOLIDITY_PATH.read_text()
    _require("contract Halo2Verifier" in source, "generated Solidity contract name changed")
    _require("function verifyProof" in source, "generated verifier does not expose verifyProof")
    _require(
        not any(line.endswith((" ", "\t")) for line in source.splitlines()),
        "generated verifier contains trailing whitespace",
    )

    abi = read_json(VERIFIER_ABI_PATH)
    _require(isinstance(abi, list), "generated verifier ABI must be an array")
    verify_entries = [
        entry
        for entry in abi
        if entry.get("type") == "function" and entry.get("name") == "verifyProof"
    ]
    _require(len(verify_entries) == 1, "generated verifier ABI must expose one verifyProof")
    input_types = [item.get("type") for item in verify_entries[0].get("inputs", [])]
    _require(input_types == ["bytes", "uint256[]"], "unexpected generated verifyProof ABI")


def _normalize_generated_solidity() -> None:
    # EZKL 23.0.5 emits two trailing spaces. Strip line-ending whitespace only so the
    # generated source remains byte-stable under Git's whitespace checks.
    lines = VERIFIER_SOLIDITY_PATH.read_text().splitlines()
    VERIFIER_SOLIDITY_PATH.write_text("\n".join(line.rstrip() for line in lines) + "\n")


def _write_verifier_manifest(manifest: dict[str, Any]) -> None:
    content = f"""# Generated Halo2 verifier

This directory is generated by `npm run prove:setup`; do not edit the verifier by hand.

- EZKL: `{manifest["ezklVersion"]}`
- Graph: `{manifest["graphVariant"]}`
- Model SHA-256: `{manifest["modelSha256"]}`
- Canonical settings SHA-256: `{manifest["settingsSha256"]}`
- SRS SHA-256: `{manifest["srsSha256"]}`
- Proving-key SHA-256: `{manifest["provingKeySha256"]}`
- Verification-key SHA-256: `{manifest["verificationKeySha256"]}`
- Solidity SHA-256: `{manifest["verifierSoliditySha256"]}`
- ABI SHA-256: `{manifest["verifierAbiSha256"]}`

The ABI was checked at generation time for `verifyProof(bytes,uint256[])`.
"""
    VERIFIER_MANIFEST_PATH.write_text(content)


def setup_pipeline() -> dict[str, Any]:
    started = time.perf_counter()
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_VERIFIER_DIR.mkdir(parents=True, exist_ok=True)
    manifest = read_manifest()
    _assert_pinned_environment(manifest)

    model_digest = _export_model()
    _require(model_digest == manifest.get("modelSha256"), "model digest differs from manifest")

    generated_settings = ezkl_cli.gen_settings(MODEL_PATH, SETTINGS_PATH)
    generated_digest = ezkl_cli.canonical_settings_sha256(generated_settings)
    expected_generated_digest = manifest.get("baseSettingsSha256", manifest.get("settingsSha256"))
    _require(
        generated_digest == expected_generated_digest,
        "generated settings differ from the Phase 1 compatibility spike",
    )

    _write_calibration_data()
    calibrated_settings = ezkl_cli.calibrate_settings(MODEL_PATH, CALIBRATION_PATH, SETTINGS_PATH)
    _validate_settings(calibrated_settings)
    settings_digest = ezkl_cli.canonical_settings_sha256(calibrated_settings)

    ezkl_cli.compile_circuit(MODEL_PATH, SETTINGS_PATH, COMPILED_CIRCUIT_PATH)
    ezkl_cli.get_srs(SETTINGS_PATH, SRS_PATH)
    ezkl_cli.setup(COMPILED_CIRCUIT_PATH, SRS_PATH, VERIFICATION_KEY_PATH, PROVING_KEY_PATH)
    ezkl_cli.create_evm_verifier(
        SETTINGS_PATH,
        SRS_PATH,
        VERIFICATION_KEY_PATH,
        VERIFIER_SOLIDITY_PATH,
        VERIFIER_ABI_PATH,
    )
    _normalize_generated_solidity()
    _validate_generated_verifier()

    manifest.update(
        {
            "arch": platform.machine(),
            "pythonVersion": platform.python_version(),
            "baseSettingsSha256": expected_generated_digest,
            "settingsSha256": settings_digest,
            "logrows": calibrated_settings["run_args"]["logrows"],
            "modelInstanceShapes": calibrated_settings["model_instance_shapes"],
            "srsSha256": sha256_file(SRS_PATH),
            "compiledCircuitSha256": sha256_file(COMPILED_CIRCUIT_PATH),
            "provingKeySha256": sha256_file(PROVING_KEY_PATH),
            "verificationKeySha256": sha256_file(VERIFICATION_KEY_PATH),
            "verifierSoliditySha256": sha256_file(VERIFIER_SOLIDITY_PATH),
            "verifierAbiSha256": sha256_file(VERIFIER_ABI_PATH),
        }
    )
    manifest["timingsSeconds"] = {"setup": round(time.perf_counter() - started, 3)}
    write_manifest(manifest)
    _write_verifier_manifest(manifest)
    return manifest


def _require_setup() -> dict[str, Any]:
    missing = [path.name for path in REQUIRED_SETUP_ARTIFACTS if not path.is_file()]
    if missing:
        missing_names = ", ".join(missing)
        raise PipelineError(
            f"missing proof setup artifacts: {missing_names}; run npm run prove:setup"
        )
    manifest = read_manifest()
    _assert_pinned_environment(manifest)
    _require(sha256_file(MODEL_PATH) == manifest.get("modelSha256"), "model digest mismatch")
    _require(
        ezkl_cli.canonical_settings_sha256(read_json(SETTINGS_PATH))
        == manifest.get("settingsSha256"),
        "settings digest mismatch",
    )
    _require(
        sha256_file(COMPILED_CIRCUIT_PATH) == manifest.get("compiledCircuitSha256"),
        "compiled-circuit digest mismatch",
    )
    _require(sha256_file(SRS_PATH) == manifest.get("srsSha256"), "SRS digest mismatch")
    _require(
        sha256_file(PROVING_KEY_PATH) == manifest.get("provingKeySha256"),
        "proving-key digest mismatch",
    )
    _require(
        sha256_file(VERIFICATION_KEY_PATH) == manifest.get("verificationKeySha256"),
        "verification-key digest mismatch",
    )
    return manifest


def _expected_eligibility(witness: list[int]) -> bool:
    age, hba1c_tenths, egfr = witness
    return age >= 18 and hba1c_tenths >= 57 and hba1c_tenths < 85 and egfr >= 60


def prove_fixture(input_path: Path, output_path: Path) -> dict[str, Any]:
    manifest = _require_setup()
    normalized = fixture_to_ezkl_input(input_path)
    witness_values = normalized["input_data"][0]
    expected_eligible = _expected_eligibility(witness_values)
    paths = artifact_paths_for_bundle(output_path, ARTIFACTS_DIR)
    write_json(paths.private_input, normalized)

    ezkl_cli.gen_witness(paths.private_input, COMPILED_CIRCUIT_PATH, paths.witness)
    started = time.perf_counter()
    ezkl_cli.prove(
        paths.witness,
        COMPILED_CIRCUIT_PATH,
        PROVING_KEY_PATH,
        SRS_PATH,
        paths.ezkl_proof,
    )
    prove_seconds = round(time.perf_counter() - started, 3)
    ezkl_cli.encode_evm_calldata(paths.ezkl_proof, paths.calldata)

    bundle = build_bundle(
        paths.ezkl_proof,
        paths.calldata,
        model_sha256=manifest["modelSha256"],
        ezkl_version=manifest["ezklVersion"],
        expected_eligible=expected_eligible,
    )
    write_bundle(output_path, bundle)

    timing_key = "proveEligible" if bundle["eligible"] else "proveIneligible"
    manifest.setdefault("timingsSeconds", {})[timing_key] = prove_seconds
    write_manifest(manifest)
    write_proof_feasibility(manifest)
    return bundle


def verify_proof_bundle(bundle_path: Path) -> dict[str, Any]:
    manifest = _require_setup()
    bundle = validate_bundle(read_json(bundle_path))
    _require(bundle["modelSha256"] == manifest.get("modelSha256"), "bundle model digest mismatch")
    _require(bundle["ezklVersion"] == manifest.get("ezklVersion"), "bundle EZKL version mismatch")

    paths = artifact_paths_for_bundle(bundle_path, ARTIFACTS_DIR)
    write_json(paths.verification_proof, proof_document_from_bundle(bundle))
    started = time.perf_counter()
    ezkl_cli.verify(SETTINGS_PATH, paths.verification_proof, VERIFICATION_KEY_PATH, SRS_PATH)
    verify_seconds = round(time.perf_counter() - started, 3)

    public_output = int(bundle["instances"][0])
    _require(bundle["eligible"] == (public_output == 1), "bundle output assertion failed")
    timing_key = "verifyEligible" if bundle["eligible"] else "verifyIneligible"
    manifest.setdefault("timingsSeconds", {})[timing_key] = verify_seconds
    write_manifest(manifest)
    write_proof_feasibility(manifest)
    return bundle
