from __future__ import annotations

from typing import Any

from artifacts import PROOF_FEASIBILITY_PATH


def _seconds(timings: dict[str, Any], key: str) -> str:
    value = timings.get(key)
    return "not measured" if value is None else f"{float(value):.3f} seconds"


def write_proof_feasibility(manifest: dict[str, Any]) -> None:
    timings = manifest.get("timingsSeconds", {})
    content = f"""# VitaPod proof feasibility

> Generated by the Phase 3 proof scripts from `prover/manifest.json`. Do not edit by hand.

The measurements below run inside the pinned native `linux/arm64` VitaPod container. The
policy is a deterministic synthetic-data demonstration, not a trained or medical model.

## Toolchain

| Item | Pinned value |
| --- | --- |
| Architecture | `{manifest.get("arch", "unknown")}` |
| Python | `{manifest.get("pythonVersion", "unknown")}` |
| ONNX | `{manifest.get("onnxVersion", "unknown")}` |
| EZKL | `{manifest.get("ezklVersion", "unknown")}` |
| Graph | `{manifest.get("graphVariant", "unknown")}` |
| Model SHA-256 | `{manifest.get("modelSha256", "unknown")}` |
| Settings SHA-256 | `{manifest.get("settingsSha256", "unknown")}` |
| Verification-key SHA-256 | `{manifest.get("verificationKeySha256", "not generated")}` |

## Measured pipeline

| Operation | Duration |
| --- | --- |
| Setup | {_seconds(timings, "setup")} |
| Prove (eligible) | {_seconds(timings, "proveEligible")} |
| Verify (eligible) | {_seconds(timings, "verifyEligible")} |
| Prove (ineligible) | {_seconds(timings, "proveIneligible")} |
| Verify (ineligible) | {_seconds(timings, "verifyIneligible")} |

`Setup` includes model export, boundary-fixture calibration, circuit compilation, SRS
retrieval, key generation, and Solidity verifier generation. SRS retrieval may use a cached
local artifact on later runs. Each `Prove` row measures the EZKL proof command; witness and
bundle preparation are excluded. Each `Verify` row measures local EZKL verification.

The generated proof bundle contains the Halo2 proof, one public `0`/`1` eligibility output,
and reproducibility metadata. It omits the source record, normalized input, witness, and
proving key.
"""
    PROOF_FEASIBILITY_PATH.parent.mkdir(parents=True, exist_ok=True)
    PROOF_FEASIBILITY_PATH.write_text(content)
